version: "3.9"

services:
  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: task-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: task-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
